# MOCK Get Data

## Setup

In [32]:
import pandas as pd
import numpy as np

In [78]:
input_dir = 'inputs/'

company_info_path = input_dir + 'company_info.csv'
monthly_returns_path = input_dir + 'monthly_returns.csv'
company_themes_path = input_dir + 'company_themes.csv'

## Create Mock Company Information

In [34]:
# Randomly generate 25 unique CIKs and put them in a dataframe
company_info = pd.DataFrame(np.random.randint(1000000, 9999999, 25), columns=['CIK'])

# Randomly assign eight industry sectors to each CIK
company_info['sector'] = np.random.choice(
    ['Energy', 'Materials', 'Industrials', 'Consumer Discretionary', 'Consumer Staples', 'Health Care', 'Financials', 'Information Technology', 'Communication Services', 'Utilities'],
    25)

# Randomly assign a market cap from 100M to 100B for each CIK
company_info['market_cap'] = np.random.randint(100, 100000, 25)

# Randomly generate three ESG scores of varying ranges/distriubtions for each
company_info['esg1'] = np.random.normal(50, 10, 25)
company_info['esg2'] = np.random.uniform(0, 100, 25)
company_info['esg3'] = np.random.standard_gamma(1, 25)

In [35]:
company_info

,CIK,sector,market_cap,esg1,esg2,esg3
0,5220704,Health Care,39611,54.703106,48.160889,0.220305
1,2332044,Utilities,82878,41.660446,97.178136,1.947844
2,9637119,Financials,98896,34.817850,46.831737,0.389516
3,3355642,Materials,23420,63.150812,81.004760,0.340540
4,1883457,Financials,37909,36.628471,1.818304,2.353531
5,2069450,Information Technology,93710,59.247939,88.082833,0.009170
6,3542095,Health Care,73549,54.320938,23.435024,0.213535
7,6649678,Health Care,68854,64.127276,34.159510,2.127681
8,9763004,Health Care,80415,44.937475,52.142473,2.905877
9,9970121,Communication Services,94857,51.042855,74.201731,0.253233
10,2476926,Utilities,41966,53.581323,19.067856,0.200630
11,2440382,Health Care,74545,36.944246,13.557946,0.180135
12,9996541,Consumer Discretionary,63960,42.670468,7.041884,0.063354
13,5577967,Consumer Staples,3062,48.392205,87.596684,1.429076
14,2626172,Energy,92191,42.048393,77.379734,3.475053
15,5134986,Industrials,76360,59.937372,63.732204,1.864255
16,9692085,Utilities,56657,54.536358,12.476436,0.182316
17,1735726,Financials,27477,45.879311,14.820601,0.339574
18,2327855,Industrials,53294,45.755165,1.065405,0.198249
19,4081732,Communication Services,13272,52.148713,35.691675,0.036936
20,9807705,Materials,9828,65.517421,47.485910,1.059469
21,4932156,Health Care,38363,42.198745,72.201077,2.532970
22,2191294,Industrials,11391,50.972694,60.013288,1.120387
23,4452226,Financials,69261,33.007741,50.800800,0.101669
24,1051688,Industrials,14867,59.051638,0.051091,0.720550

In [36]:
# Save mock data to a csv file
company_info.to_csv(company_info_path, index=False)

## Create Mock Monthly Returns Data

In [72]:
# For each month from 2013-01 to 2020-01, randomly generate a return for each CIK
monthly_returns = pd.DataFrame(columns=['CIK', 'date', 'ret'])

dates = pd.date_range(start='2013-01-01', end='2020-01-01', freq='MS')

for cik in company_info['CIK']:
  # Generate a set of monthly returns for each CIK
  curr_monthly_returns = pd.DataFrame({
      'CIK': [cik for _ in range(len(dates))],
      'date': dates,
      'ret': np.random.normal(0, 1, len(dates))})
  
  # Append the current CIK's monthly returns to the dataframe
  monthly_returns = pd.concat([monthly_returns, curr_monthly_returns])

# Rescale the returns to be between -1 and 1
monthly_returns['ret'] = monthly_returns['ret'] / monthly_returns['ret'].abs().max()

# Add predicted returns for each CIK
monthly_returns['pred_ret1'] = monthly_returns['ret'] + np.random.normal(0, 0.2, len(monthly_returns)) - 0.1
monthly_returns['pred_ret2'] = monthly_returns['ret'] + np.random.normal(0, 0.2, len(monthly_returns)) - 0.1
monthly_returns['pred_ret3'] = monthly_returns['ret'] + np.random.normal(0, 0.2, len(monthly_returns)) - 0.1

In [73]:
monthly_returns

        CIK       date       ret  pred_ret1  pred_ret2  pred_ret3
0   5220704 2013-01-01  0.042038  -0.000309  -0.047066  -0.413661
1   5220704 2013-02-01 -0.098542  -0.394995   0.163334  -0.315712
2   5220704 2013-03-01 -0.210259  -0.364391  -0.291918  -0.145896
3   5220704 2013-04-01  0.038368  -0.005837  -0.150492   0.006581
4   5220704 2013-05-01  0.151490   0.122270  -0.050050   0.602736
..      ...        ...       ...        ...        ...        ...
80  1051688 2019-09-01  0.820370   1.100433   0.532494   0.940478
81  1051688 2019-10-01  0.243218   0.135231   0.458307   0.240781
82  1051688 2019-11-01 -0.221654  -0.303337  -0.308688  -0.138715
83  1051688 2019-12-01 -0.032243  -0.045724  -0.448300   0.201187
84  1051688 2020-01-01 -0.026156  -0.053294  -0.076825   0.135615

[2125 rows x 6 columns]

In [74]:
monthly_returns.to_csv(monthly_returns_path, index=False)

## Create Mock Themes

In [75]:
# Randomly generate pairs of CIKs and investing themes
company_themes = pd.DataFrame(columns=['CIK', 'theme'])

themes = ['environment', 'social', 'governance', 'energy', 'ethics']

for cik in company_info['CIK']:
  # Select a random number of themes for each CIK
  num_themes = np.random.randint(0, 10)

  # Generate a set of themes for each CIK
  curr_company_themes = pd.DataFrame({
      'CIK': [cik for _ in range(num_themes)],
      'theme': np.random.choice(themes, num_themes)})
  
  # Append the current CIK's themes to the dataframe
  company_themes = pd.concat([company_themes, curr_company_themes])

In [79]:
company_themes

        CIK       theme
0   5220704      energy
0   2332044      social
1   2332044      ethics
2   2332044  governance
3   2332044      social
..      ...         ...
0   1051688      social
1   1051688      energy
2   1051688      ethics
3   1051688      social
4   1051688  governance

[116 rows x 2 columns]

In [80]:
company_themes.to_csv(company_themes_path, index=False)